POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Brad_16",
    "lastName": "Pitt",
    "email": "brad_471@gmail.com",
    "password":"123123",
    "birthday": "1963-12-18",
    "isMale": true
}